baseURL: "https://bennysbytes.dev/"
title: Benny's Bytes
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "Benny's Bytes"
  description: "Benny's Bytes"
  keywords: [Blog, Ben Vilnis, Benny's Bytes]
  author: "Ben Vilnis"
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    disableHLJS: true
    disableFingerprinting: true
    favicon: "assets/favicon.ico"
    favicon16x16: "assets/favicon-16x16.png"
    favicon32x32: "assets/favicon-32x32.png"
    apple_touch_icon: "assets/apple-touch-icon.png"
    safari_pinned_tab: "assets/favicon.ico"

  label:
    text: "Benny's Bytes"
    icon: "assets/favicon.ico"
    iconHeight: 35

  # home-info mode
  homeInfoParams:
    Title: "Hello, friend."
    Content: "My name is Ben. I'm an engineering manager with a background in DevOps and Site Reliability Engineering. I've been fortunate to work at some great companies and learn from some amazing people. Here's some of the lessons I've learned along the way."

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/benvilnis/"
    - name: x
      url: "https://x.com/bennysbanter"
    - name: github
      url: "https://github.com/bvilnis"

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - name: Archive
      url: archives
      weight: 5
    - name: Search
      url: search/
      weight: 10
    - name: CV
      url: "https://cv.bennysbytes.dev"
      weight: 15

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
